# **集成模型**

## 导入数据及相关库

In [23]:
import pandas as pd
import numpy as np

day1 = pd.read_csv('C:/Users/dell/Desktop/day1_data_all.csv')

X = day1.drop(['status'],axis =1)
Y = day1.loc[:,'status']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3,random_state = 2018)

from sklearn.metrics import roc_auc_score

## XGBoost

In [24]:
from xgboost.sklearn import XGBClassifier 

xgbc =  XGBClassifier(random_state = 2018)
xgbc = xgbc.fit(x_train,y_train)
xgbc.score(x_test,y_test)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.7855641205325858

In [25]:
pre_test = xgbc.predict(x_test)
auc_score = roc_auc_score(y_test,pre_test)
auc_score

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.6431606209508309

## 随机森林

In [29]:
from sklearn.ensemble import RandomForestClassifier 
rf = RandomForestClassifier()
rf = rf.fit(x_train,y_train)
rf.predict(x_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
rf.score(x_test,y_test)

0.7687456201822004

In [22]:
pre_test = rf.predict(x_test)
auc_score = roc_auc_score(y_test,pre_test)
auc_score

0.6023376941775427

## LightGBM

In [30]:
import lightgbm as lgb
lgbc = lgb.LGBMClassifier()
lgbc.fit(x_train,y_train)
lgbc.predict(x_test)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [31]:
lgbc.score(x_test,y_test)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.7701471618780659

In [32]:
pre_test = lgbc.predict(x_test)
auc_score = roc_auc_score(y_test,pre_test)
auc_score

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.6310118097503468

## GBDT

In [36]:
from sklearn.ensemble import GradientBoostingClassifier 
gbdtc = GradientBoostingClassifier()
gbdtc.fit(x_train,y_train)
gbdtc.predict(x_test)

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [37]:
gbdtc.score(x_test,y_test)

0.779957953749124

In [38]:
pre_test = gbdtc.predict(x_test)
auc_score = roc_auc_score(y_test,pre_test)
auc_score

0.6375661168664518